---
- name: saving image to azure cloud
  hosts: all
  become: yes
  ignore_errors: yes
  vars: 
    uuid: <insert uuid-from-imagebuilder>
  tasks: 
    - name: composing image to be saved 
      command: composer-cli compose image {{ uuid }}
      args:
        chdir: <define the directory where you want the image to be saved>
  

- name: pushing image to azure cloud 
  hosts: all
  vars: 
    user: <insert user email>
    password: <insert user password>
    account: <insert-azure-account>
    container: <insert-azure-container-account>
    uuid_disk_vhd: <insert UUID***-disk.vhd>
  tasks:
    - name: logging into azure 
      command:
        cmd: az login -u {{ user }} -p {{ password }}
          
    - name: push the image to Azure and create an instance
      command: az storage blob upload --account-name {{ account }} --container-name {{ container }} --file {{ uuid_disk_vhd }}  --name {{ uuid_disk_vhd }} --type page
      args:
         chdir: <define where the directory of the image is saved>
